# Data Split
    The way you splitting your data into training and testing and others


In [1]:
from sklearn.model_selection import train_test_split
import numpy as np

In [2]:
'''
    The most of use is train_test_split which divide the data into train and test
'''

X = np.arange(120).reshape(60, 2)
y = np.arange(60).reshape(60,1)
X.shape

(60, 2)

In [3]:
X[:10, :]

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [4]:
X_train, X_test, y_train,  y_test = train_test_split(X,y,test_size=.5, shuffle=True)

In [5]:
X_train.shape

(30, 2)

In [6]:

X_test.shape

(30, 2)

In [7]:
y_train.shape

(30, 1)

In [8]:
y_test.shape

(30, 1)

In [9]:
from sklearn.model_selection import KFold

In [10]:
'''
    KFold used to split your data to some flods as you need
    random_state used because the same data will be floded if use other algorithm
    This help you to train and test alot because its use some of data in train then in next split use it as test
'''
X = np.arange(120).reshape(60, 2)
y = np.arange(60).reshape(60,1)
X.shape

(60, 2)

In [11]:
kf = KFold(n_splits=4, random_state=44, shuffle =True)

In [12]:

for train_index,test_index in kf.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print('X_train \n' , X_train)
    print('X_test \n' , X_test)
    print('y_train \n' ,y_train)
    print('y_test \n' , y_test)

TRAIN: [ 1  2  3  7  8 10 12 14 16 18 19 20 21 22 23 25 26 28 29 30 31 32 33 34
 35 36 37 38 40 41 42 43 45 46 47 48 49 51 52 53 54 55 57 58 59] TEST: [ 0  4  5  6  9 11 13 15 17 24 27 39 44 50 56]
X_train 
 [[  2   3]
 [  4   5]
 [  6   7]
 [ 14  15]
 [ 16  17]
 [ 20  21]
 [ 24  25]
 [ 28  29]
 [ 32  33]
 [ 36  37]
 [ 38  39]
 [ 40  41]
 [ 42  43]
 [ 44  45]
 [ 46  47]
 [ 50  51]
 [ 52  53]
 [ 56  57]
 [ 58  59]
 [ 60  61]
 [ 62  63]
 [ 64  65]
 [ 66  67]
 [ 68  69]
 [ 70  71]
 [ 72  73]
 [ 74  75]
 [ 76  77]
 [ 80  81]
 [ 82  83]
 [ 84  85]
 [ 86  87]
 [ 90  91]
 [ 92  93]
 [ 94  95]
 [ 96  97]
 [ 98  99]
 [102 103]
 [104 105]
 [106 107]
 [108 109]
 [110 111]
 [114 115]
 [116 117]
 [118 119]]
X_test 
 [[  0   1]
 [  8   9]
 [ 10  11]
 [ 12  13]
 [ 18  19]
 [ 22  23]
 [ 26  27]
 [ 30  31]
 [ 34  35]
 [ 48  49]
 [ 54  55]
 [ 78  79]
 [ 88  89]
 [100 101]
 [112 113]]
y_train 
 [[ 1]
 [ 2]
 [ 3]
 [ 7]
 [ 8]
 [10]
 [12]
 [14]
 [16]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [25]
 [26]
 [28]
 [2