# Scale Data
This is a way to standard your data in a range like [0-1] instead of some features with 1 or 0 and others with 10000 or greater or less and so on

also its help the operation on the number to be faster

In [1]:
from sklearn.preprocessing import StandardScaler

In [2]:
'''
    StandardScaler use standard division
    its work as (X - mean(X)) / standard_division(X)
    mean(x) sum of X over # number of them
'''
import numpy as np
data = [
        [50, 30],
        [20, 40], 
        [1000, 2], 
        [1, 40000]
    ]
np.std(data)

13178.638486557516

In [3]:
data = StandardScaler().fit_transform(data)

In [4]:
data

array([[-0.51462273, -0.57700346],
       [-0.58552368, -0.57642577],
       [ 1.73057403, -0.57862102],
       [-0.63042762,  1.73205025]])

In [5]:
from sklearn.preprocessing import MinMaxScaler

In [6]:
'''
    MinMaxScaler divide by max - min
    its work as (X - mean(X)) / max - min
    
'''
data = [
        [0, 30],
        [20, 40], 
        [40, 2], 
        [30, 40000]
    ]


In [7]:
data = MinMaxScaler().fit_transform(data)
data

array([[0.00000000e+00, 7.00035002e-04],
       [5.00000000e-01, 9.50047502e-04],
       [1.00000000e+00, 0.00000000e+00],
       [7.50000000e-01, 1.00000000e+00]])

In [8]:
from sklearn.preprocessing import Normalizer

In [9]:
'''
    Normalizer use sum of each row and divide each number by this sum if norm='l1'
    Normalizer use sum of each row number to power of 2 and divide each number by this sqrt of this sum if norm='l2'
  Normalizer use max number of each row and divide by it if norm='max'
    
'''
X = [[4, 1, 2, 2],
     [1, 3, 9, 3],
     [5, 7, 5, 1]]

In [10]:
X = Normalizer(norm='max').fit_transform(X)
X

array([[1.        , 0.25      , 0.5       , 0.5       ],
       [0.11111111, 0.33333333, 1.        , 0.33333333],
       [0.71428571, 1.        , 0.71428571, 0.14285714]])

In [11]:
from sklearn.preprocessing import MaxAbsScaler

In [12]:
'''
    the same as Normalizer with norm='max' but with columns
    divide each columns number by the max of this column
'''
X = [[4, 1, 2, 2],
     [1, 3, 9, 3],
     [5, 7, 5, 1]]

In [13]:
X = MaxAbsScaler().fit_transform(X)
X

array([[0.8       , 0.14285714, 0.22222222, 0.66666667],
       [0.2       , 0.42857143, 1.        , 1.        ],
       [1.        , 1.        , 0.55555556, 0.33333333]])

In [14]:
from sklearn.preprocessing import Binarizer

In [15]:
'''
    all values grated than 3 be 1 else be 0 and you choose what is your threshold
'''
X = [[4, 1, 2, .2],
     [1, 3, 9, 3],
     [5, 7, 5, 1]]

In [16]:
X = Binarizer(threshold=3).fit_transform(X)
X

array([[1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 1., 1., 0.]])

In [20]:
from sklearn.preprocessing import PolynomialFeatures

In [21]:
'''
    instead of manual features mapping we use PolynomialFeatures function
'''
X = [[4, 1, 2],
     [1, 3, 9],
     [5, 7, 5]]

In [22]:
X = PolynomialFeatures(degree=2, include_bias=False, interaction_only=True).fit_transform(X)
X

array([[ 4.,  1.,  2.,  4.,  8.,  2.],
       [ 1.,  3.,  9.,  3.,  9., 27.],
       [ 5.,  7.,  5., 35., 25., 35.]])