In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, median_absolute_error

In [2]:
df = pd.read_csv('satf.csv')
X = np.array(df.iloc[:,1])
y = np.array(df.iloc[:,-1])
X = np.reshape(X, (X.shape[0],1))
y = np.reshape(y, (y.shape[0],1))

In [3]:
X_train, X_test, y_train, y_test  = train_test_split(X,y, test_size=.2, random_state = 0)

In [4]:
from sklearn.linear_model import LinearRegression


In [5]:
LR = LinearRegression()
LR.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [6]:
pred = LR.predict(X_test)

In [7]:
print(pred[:5])

[[2.92715848]
 [3.26291838]
 [2.94314705]
 [3.0763851 ]
 [3.30555456]]


In [8]:
print(y_test[:5])

[[2.4 ]
 [3.38]
 [2.4 ]
 [3.41]
 [3.48]]


In [9]:
LR.score(X_train, y_train)

0.44271521011617154

In [10]:
LR.score(X_test, y_test)

0.4102240345807987

In [11]:
mean_absolute_error(pred, y_test)

0.29680351516463255

In [12]:
mean_squared_error(pred, y_test)

0.12814213522395623

In [13]:
median_absolute_error(pred, y_test)

0.2519235984217625

In [14]:
df = pd.read_csv('satf.csv')
print(df.head())
X = np.array(df.iloc[:,:-1])
y = np.array(df.iloc[:,-1])
y = np.reshape(y, (y.shape[0],1))

   high_GPA  math_SAT  verb_SAT  comp_GPA  univ_GPA
0      3.45       643       589      3.76      3.52
1      2.78       558       512      2.87      2.91
2      2.52       583       503      2.54      2.40
3      3.67       685       602      3.83      3.47
4      3.24       592       538      3.29      3.47


In [15]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=.2, random_state=0)

In [16]:
LR = LinearRegression()

In [17]:
LR.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [18]:
pred = LR.predict(X_test)

In [19]:
LR.score(X_test, y_test)

0.9149101142887585

In [20]:
LR.score(X_train, y_train)

0.8793607907673509

In [21]:
print(pred[:5])

[[2.6670713 ]
 [3.26128004]
 [2.66000098]
 [3.50702704]
 [3.33485598]]


In [22]:
print(y_test[:5])

[[2.4 ]
 [3.38]
 [2.4 ]
 [3.41]
 [3.48]]


In [23]:
mean_absolute_error(pred, y_test)

0.11580859161663966

In [24]:
mean_squared_error(pred, y_test)

0.018487697499254357

In [25]:
median_absolute_error(pred, y_test)

0.1187199601006772

In [26]:
from sklearn.linear_model import Ridge
from sklearn.model_selection import train_test_split

In [27]:
df = pd.read_csv('satf.csv')

In [28]:
X = np.array(df.iloc[:, :-1])
y = np.array(df.iloc[:, -1])
print(X.shape)
y = np.reshape(y, (y.shape[0],1))
print(y.shape)

(105, 4)
(105, 1)


In [29]:
R = Ridge(alpha=.1, random_state=4)

In [30]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=.2, random_state=4)

In [31]:
R.fit(X_train, y_train)

Ridge(alpha=0.1, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=4, solver='auto', tol=0.001)

In [32]:
pred = R.predict(X_test)

In [33]:
print(pred[:5])

[[3.64522394]
 [3.15832667]
 [3.76689832]
 [3.56169856]
 [3.34116878]]


In [34]:
print(y_test[:5])

[[3.51]
 [3.01]
 [3.73]
 [3.59]
 [3.42]]


In [35]:
print(R.score(X_train, y_train))

0.8893901954230975


In [36]:
print(R.score(X_test, y_test))

0.8713920014427639


In [37]:
mean_absolute_error(pred, y_test)

0.15403338751589638

In [38]:
mean_squared_error(pred, y_test)

0.035208728885743334

In [39]:
median_absolute_error(pred, y_test)

0.12123252462567091

In [40]:
from sklearn.datasets import load_boston

In [41]:
df = load_boston()

In [42]:
X = df.data

In [43]:
y = df.target

In [44]:
df.feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [45]:
LR = LinearRegression()
R = Ridge(alpha=.2)

In [46]:
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state=4, test_size=.2)

In [47]:
LR.fit(X_train, y_train)
R.fit(X_train, y_train)

Ridge(alpha=0.2, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=None, solver='auto', tol=0.001)

In [48]:
predLR = LR.predict(X_test)
predR = R.predict(X_test)

In [49]:
print(predLR[:5])

[12.07495986 26.9894969  17.58803353 18.15584511 36.92091659]


In [50]:
print(predR[:5])

[11.96174432 26.93350074 17.50339656 17.90591787 36.85068965]


In [51]:
print(y_test[:5])

[16.5 24.8 17.4 19.3 37.6]


In [52]:
mean_absolute_error(predLR, y_test)

3.3677909837965796

In [53]:
mean_absolute_error(predR, y_test)

3.3576713717628603

In [54]:
mean_squared_error(predLR, y_test)

25.41958712682191

In [55]:
mean_squared_error(predR, y_test)

25.491958110492924

In [56]:
median_absolute_error(predLR, y_test)

2.4527007662819873

In [57]:
median_absolute_error(predR, y_test)

2.430430730932345

In [58]:
LR.score(X_test, y_test)

0.7263451459702503

In [59]:
R.score(X_test, y_test)

0.7255660353232649