In [1]:
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split
from sklearn.svm import SVR
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import median_absolute_error
import numpy as np
import pandas as pd

In [2]:
df = load_boston()

In [3]:
X = df.data
X.shape

(506, 13)

In [4]:
y = df.target
y.shape

(506,)

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=4)

In [6]:
SVRModel = SVR(C = 1.0 ,epsilon=0.1,kernel = 'rbf') 

In [7]:
SVRModel.fit(X_train, y_train)

/home/abdelrahman/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1,
    gamma='auto_deprecated', kernel='rbf', max_iter=-1, shrinking=True,
    tol=0.001, verbose=False)

In [8]:
y_pred = SVRModel.predict(X_test)

In [9]:
print("The first 5  predictive values are \n", y_pred[:5])

The first 5  predictive values are 
 [21.26172451 21.2617299  21.24107275 21.26471681 21.29901204]


In [10]:
print("The first 5  actuall values are \n", y_test[:5])

The first 5  actuall values are 
 [16.5 24.8 17.4 19.3 37.6]


In [11]:
print('SVRModel Train Score is : ' , SVRModel.score(X_train, y_train))
print('SVRModel Test Score is : ' , SVRModel.score(X_test, y_test))

SVRModel Train Score is :  0.1548755640115046
SVRModel Test Score is :  -0.030111930218872592


In [12]:
MAEValue = mean_absolute_error(y_test, y_pred, multioutput='uniform_average') # it can be raw_values
print('Mean Absolute Error Value is : ', MAEValue)

Mean Absolute Error Value is :  6.800314166792825


In [13]:
MSEValue = mean_squared_error(y_test, y_pred, multioutput='uniform_average') # it can be raw_values
print('Mean Squared Error Value is : ', MSEValue)

Mean Squared Error Value is :  95.68629817810827


In [14]:
MdSEValue = median_absolute_error(y_test, y_pred)
print('Median Squared Error Value is : ', MdSEValue )

Median Squared Error Value is :  4.195001070706588


In [15]:
df = pd.read_csv('Earthquakes.csv')

In [16]:
df.describe()

latitude    longitude        depth          mag          gap  \
count  1369.000000  1369.000000  1369.000000  1369.000000  1369.000000   
mean     -1.117302   119.207969   102.069072     4.496275   100.971512   
std       5.605702    10.028394   129.415379     0.377192    44.781584   
min     -11.762200    95.113500     4.000000     3.900000    13.000000   
25%      -7.026200   112.938000    24.610000     4.200000    71.000000   
50%       0.268400   123.957300    53.860000     4.400000    95.000000   
75%       3.541300   126.788100   121.110000     4.600000   128.000000   
max       9.268100   128.317100   621.700000     6.900000   324.000000   

              dmin          rms  horizontalError   depthError     magError  \
count  1369.000000  1369.000000      1369.000000  1369.000000  1368.000000   
mean      2.326909     0.852768         8.227684     6.678305     0.121450   
std       2.286374     0.260124         2.622920     3.829167     0.050303   
min       0.008000     0.130000         2.400000     0.600000     0.034000   
25%       1.310000     0.670000         6.500000     3.600000     0.085000   
50%       2.063000     0.830000         7.900000     7.000000     0.116000   
75%       2.928000     1.030000         9.500000     8.900000     0.148000   
max      56.265000     1.640000        29.300000    33.700000     0.532000   

             meter  
count  1368.000000  
mean     30.986111  
std      30.446167  
min       1.000000  
25%      13.000000  
50%      20.000000  
75%      37.000000  
max     269.000000

In [17]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

In [18]:

imp = SimpleImputer(missing_values=np.nan, strategy='mean')
imp = imp.fit(df)
df = imp.transform(df)

In [19]:
X = df[:, :-1]
X.shape

(1369, 10)

In [20]:
y = df[:,-1]

In [21]:
y.shape

(1369,)

In [22]:
SCLAR = StandardScaler()

In [23]:
X = SCLAR.fit_transform(X)

In [24]:
clf = SVR(kernel = 'linear')

In [25]:
clf.fit(X, y)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1,
    gamma='auto_deprecated', kernel='linear', max_iter=-1, shrinking=True,
    tol=0.001, verbose=False)

In [26]:
y_pred = clf.predict([[90,12,12,-5,54,0.3,0.9,3.5,16.2,10]])
abs(y_pred)

array([133.24880322])

In [27]:
df = pd.read_csv('houses.csv')

In [28]:
df.head()

bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view  \
0       3.0       1.00       1180.0    5650.0     1.0         0.0   0.0   
1       3.0       2.25       2570.0    7242.0     2.0         0.0   0.0   
2       2.0       1.00        770.0   10000.0     1.0         0.0   0.0   
3       4.0       3.00       1960.0    5000.0     1.0         0.0   0.0   
4       3.0       2.00       1680.0    8080.0     1.0         0.0   0.0   

   condition  grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0        3.0    7.0      1180.0            0.0    1955.0           0.0   
1        3.0    7.0      2170.0          400.0    1951.0        1991.0   
2        3.0    6.0       770.0            0.0    1933.0           0.0   
3        5.0    7.0      1050.0          910.0    1965.0           0.0   
4        3.0    8.0      1680.0            0.0    1987.0           0.0   

   zipcode      lat     long  sqft_living15  price  
0  98178.0  47.5112 -122.257         1340.0  22.19  
1  98125.0  47.7210 -122.319         1690.0  53.80  
2  98028.0  47.7379 -122.233         2720.0  18.00  
3  98136.0  47.5208 -122.393         1360.0  60.40  
4  98074.0  47.6168 -122.045         1800.0  51.00

In [29]:
df.describe()

bedrooms   bathrooms  sqft_living       sqft_lot      floors  \
count  999.000000  999.000000   999.000000     999.000000  999.000000   
mean     3.349349    2.045796  2051.397397   14707.242242    1.446947   
std      0.852367    0.721983   888.351113   28975.077254    0.517420   
min      0.000000    0.000000   380.000000     649.000000    1.000000   
25%      3.000000    1.500000  1405.000000    5419.000000    1.000000   
50%      3.000000    2.000000  1900.000000    8040.000000    1.000000   
75%      4.000000    2.500000  2475.000000   11508.500000    2.000000   
max      7.000000    5.000000  6070.000000  315374.000000    3.500000   

       waterfront        view   condition       grade   sqft_above  \
count  999.000000  999.000000  999.000000  999.000000   999.000000   
mean     0.008008    0.237237    3.464464    7.605606  1750.233233   
std      0.089173    0.765472    0.689521    1.160734   790.466905   
min      0.000000    0.000000    1.000000    4.000000   380.000000   
25%      0.000000    0.000000    3.000000    7.000000  1190.000000   
50%      0.000000    0.000000    3.000000    7.000000  1540.000000   
75%      0.000000    0.000000    4.000000    8.000000  2135.000000   
max      1.000000    4.000000    5.000000   12.000000  6070.000000   

       sqft_basement     yr_built  yr_renovated       zipcode         lat  \
count     999.000000   999.000000    999.000000    999.000000  999.000000   
mean      301.164164  1969.030030     81.830831  98074.441441   47.549720   
std       451.023402    28.198607    395.767918     52.545832    0.141558   
min         0.000000  1900.000000      0.000000  98001.000000   47.177500   
25%         0.000000  1952.000000      0.000000  98032.000000   47.443000   
50%         0.000000  1974.000000      0.000000  98058.000000   47.563600   
75%       580.000000  1992.000000      0.000000  98116.000000   47.673400   
max      2060.000000  2015.000000   2014.000000  98199.000000   47.777600   

             long  sqft_living15       price  
count  999.000000     999.000000  999.000000  
mean  -122.207406    1986.813814   52.071452  
std      0.139564     670.723475   33.974907  
min   -122.490000     830.000000    8.000000  
25%   -122.322500    1490.000000   30.980000  
50%   -122.218000    1850.000000   43.500000  
75%   -122.118000    2360.000000   63.446250  
max   -121.709000    4760.000000  308.000000

In [30]:
imp = SimpleImputer(missing_values=np.nan, strategy='mean')
imp = imp.fit(df)
df = imp.transform(df)

In [31]:
X = df[:,:-1]

In [32]:
X.shape

(1000, 17)

In [33]:
y = df[:,-1]

In [34]:
y.shape

(1000,)

In [35]:
sc = StandardScaler()
X = sc.fit_transform(X)

In [36]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [37]:
clf = SVR(kernel = 'linear')
clf.fit(X_train, y_train)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1,
    gamma='auto_deprecated', kernel='linear', max_iter=-1, shrinking=True,
    tol=0.001, verbose=False)

In [38]:
y_pred = clf.predict(X_test) 

In [39]:
print("The first 5  predictive values are \n", y_pred[:5])

The first 5  predictive values are 
 [24.23578877 52.09680719 39.86151573 22.15951441  0.78553309]


In [40]:
print("The first 5  actual values are \n", y_pred[:5])

The first 5  actual values are 
 [24.23578877 52.09680719 39.86151573 22.15951441  0.78553309]


In [41]:
mean_absolute_error(y_test, y_pred)

9.624347647739345

In [42]:
mean_squared_error(y_pred, y_test)

311.8937346126804